# Generated by Django 5.1.7 on 2025-03-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='image',
            new_name='img',
        ),
    ]
